### ISSUE TITLE
"Video walkthroughs" section on /q still not working on Safari

### ISSUE THREAD

**Issue by siim-m** [sunday-afternoon-design/coldcard#1]
- Chrome on the left
- Safari on the right - this heading is just followed by a bunch of black space

<img width="3360" alt="image" src="https://github.com/user-attachments/assets/80efe714-98fe-4733-9ac2-b39793801885">

**Comment by lebanesehodl** [comment]
Strange, that’s not showing up on my safari. Which version you running?

**Comment by siim-m** [comment]
Never mind, works after clearing my cache 😄
