### ISSUE TITLE
"Shop Q" and "Shop Mk4" link issues

### ISSUE THREAD

**Issue by siim-m** [sunday-afternoon-design/coldcard#2]
- These are currently `<h3>`'s but should be links so we can direct them to the store
- When I changed them to `<a>`, they lost their styling
- Even as `<a>` tags, they are not clickable. At first glance seems like a `z-index` issue?

<img width="1074" alt="image" src="https://github.com/user-attachments/assets/aebdea00-7a82-47d7-b012-dd7dcfa39014">

**Comment by siim-m** [comment]
Also, positioning is still a bit awkward on mobile:


<img width="956" alt="image" src="https://github.com/user-attachments/assets/cc99c699-fb1e-4e0d-b60e-493e2aad827e">

**Comment by SimonFrr** [comment]
this makes the links in the hero section clickable (with `href="#"`)
https://github.com/sunday-afternoon-design/coldcard/commit/3c6a73e177c97eb624772042e77d6634c0471097

**Comment by SimonFrr** [comment]
this fixes the way the hero "buy x" buttons look
https://github.com/sunday-afternoon-design/coldcard/commit/3d17bef6007ca87fc45f24c9ec1306d15458db55

**Comment by siim-m** [comment]
Works
