### ISSUE TITLE
Footer link issues

### ISSUE THREAD

**Issue by siim-m** [sunday-afternoon-design/coldcard#3]
- These are currently bare `<li>`'s
- When I turn them into `<li><a href="#">...</a></li>`, they lose their styling

<img width="659" alt="image" src="https://github.com/user-attachments/assets/f87a4ea4-87cd-48e9-bbcd-55cd6233929a">

**Comment by SimonFrr** [comment]
This fixes the links: https://github.com/sunday-afternoon-design/coldcard/commit/d298b9b0bba7eb66c064c4c8aac132e6f0352763

Not entirely sure about the URLs, but they can just be replaced in the href attr now!

**Comment by siim-m** [comment]
Perfect, thanks!
