### ISSUE TITLE
GT Planar font missing symbols?

### ISSUE THREAD

**Issue by siim-m** [sunday-afternoon-design/coldcard#5]
For example here, ampersand is rendered as a serif font. I think it might be the limitation of the trial files that were included? Testing it on this site, it seems to have it: https://www.grillitype.com/typeface/gt-planar

<img width="336" alt="image" src="https://github.com/user-attachments/assets/277746f0-2289-4c92-a609-427d831c3a36">

**Comment by siim-m** [comment]
I have tweaked the CSS to fall back to sans-serif so it looks OK but would be good to get the licensed font still. Do you provide it or do we have to buy ourselves?

**Comment by SimonFrr** [comment]
[GT Planar.zip](https://github.com/user-attachments/files/16271104/GT.Planar.zip)

**Comment by SimonFrr** [comment]
[GT Planar.zip](https://github.com/user-attachments/files/16271116/GT.Planar.zip)

@siim-m here are the font files—however it's not a free font so you are supposed to license it, their website has all the details: https://www.grillitype.com/shops/gt-planar

**Comment by SimonFrr** [comment]
Ignore my previous comments—indeed these issues occur because you are using a trial version of GT Planar, you need to buy a license for the full version, all details are here: https://www.grillitype.com/shops/gt-planar

**Comment by siim-m** [comment]
No probs, will ask NVK to purchase.
