### ISSUE TITLE
Video carousel UX

### ISSUE THREAD

**Issue by siim-m** [sunday-afternoon-design/coldcard#6]
After feeding the carousel with some more video URLs, I've noticed:

- UX is a bit awkward - you can start playing a video but then it just scrolls away.
- Sometimes it seems to stop when hovering with mouse but not always... Maybe better to have "next" and "previous" buttons with arrows instead of auto scroll?
- The clipped corners shape cuts off some of the video. Perhaps normal rectangle "cards" with slightly rounded corners would work better here? But open to other suggestions of course.
- Height of the items is inconsistent when the titles span a different number of lines.

Link to screen recording: https://drive.google.com/file/d/12JyM9UyEhJXHuX-qwcS6-YgmzPZl3dBU/view?usp=sharing

**Comment by lebanesehodl** [comment]
Agree the YouTube carousel UX is a bit awkward. We suggest the following

**Comment by lebanesehodl** [comment]
Totally agree the YouTube carousel is awkward and suggest the following change:

- As per your suggestion, kill autoscroll and go back to a previous design iteration with arrows to go "next" and "previous"
- We think it's better to keep the clipped corners for design consistency as they don't impair visibility of the videos very much.
- Will fix height of the items and keep consistent by shortening title names.

Fixes will be submitted today.
